services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
    networks:
      - gofies
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://nginx/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: 
      - .env
    networks:
      - gofies

    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://nginx/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - gofies
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 5s
      timeout: 5s
      retries: 5

  router01:
    build: 
      context: ./database/mongodb-build
    container_name: router-01
    command: mongos --port 27117 --configdb rs-config-server/configsvr01:27119,configsvr02:27120,configsvr03:27121 --bind_ip_all --keyFile /data/mongodb-keyfile
    ports:
      - 27117:27117
    restart: always
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_router01_db:/data/db
      - ./database/persistant/mongodb_cluster_router01_config:/data/configdb
    networks:
      - gofies
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27117", "--eval", "db.runCommand({ connectionStatus: 1 })"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  router02:
    build: 
      context: ./database/mongodb-build
    container_name: router-02
    command: mongos --port 27118 --configdb rs-config-server/configsvr01:27119,configsvr02:27120,configsvr03:27121 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_router02_db:/data/db
      - ./database/persistant/mongodb_cluster_router02_config:/data/configdb
    ports:
      - 27118:27118
    restart: always
    links:
      - router01
    networks:
      - gofies
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27118", "--eval", "db.runCommand({ connectionStatus: 1 })"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  configsvr01:
    build: 
      context: ./database/mongodb-build
    container_name: mongo-config-01 
    command: mongod --port 27119 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts 
      - ./database/persistant/mongodb_cluster_configsvr01_db:/data/db
      - ./database/persistant/mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27119:27119
    restart: always
    links:
      - shard01-a
      - shard02-a
      - shard03-a
      - configsvr02
      - configsvr03
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27119", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

  configsvr02:
    build: 
      context: ./database/mongodb-build
    container_name: mongo-config-02 
    command: mongod --port 27120 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_configsvr02_db:/data/db
      - ./database/persistant/mongodb_cluster_configsvr02_config:/data/configdb
    ports:
      - 27120:27120
    restart: always
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27120", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

  configsvr03:
    build: 
      context: ./database/mongodb-build
    container_name: mongo-config-03 
    command: mongod --port 27121 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_configsvr03_db:/data/db
      - ./database/persistant/mongodb_cluster_configsvr03_config:/data/configdb
    ports:
      - 27121:27121
    restart: always
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27121", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

  shard01-a:
    build: 
      context: ./database/mongodb-build
    container_name: shard-01-node-a
    command: mongod --port 27122 --shardsvr --replSet rs-shard-01 --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_shard01_a_db:/data/db
      - ./database/persistant/mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27122:27122
    restart: always
    links:
      - shard01-b
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27122", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

  shard01-b:
    build: 
      context: ./database/mongodb-build
    container_name: shard-01-node-b
    command: mongod --port 27123 --shardsvr --replSet rs-shard-01 --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_shard01_b_db:/data/db
      - ./database/persistant/mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27123:27123
    restart: always
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27123", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

  shard02-a:
    build: 
      context: ./database/mongodb-build
    container_name: shard-02-node-a
    command: mongod --port 27125 --shardsvr --replSet rs-shard-02 --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_shard02_a_db:/data/db
      - ./database/persistant/mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27125:27125
    restart: always
    links:
      - shard02-b
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27125", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

  shard02-b:
    build: 
      context: ./database/mongodb-build
    container_name: shard-02-node-b
    command: mongod --port 27126 --shardsvr --replSet rs-shard-02 --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_shard02_b_db:/data/db
      - ./database/persistant/mongodb_cluster_shard02_b_config:/data/configdb
    ports:
      - 27126:27126
    restart: always
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27126", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

  shard03-a:
    build: 
      context: ./database/mongodb-build
    container_name: shard-03-node-a
    command: mongod --port 27128 --shardsvr --replSet rs-shard-03 --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_shard03_a_db:/data/db
      - ./database/persistant/mongodb_cluster_shard03_a_config:/data/configdb
    ports:
      - 27128:27128
    restart: always
    links:
      - shard03-b
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27128", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s
      
  shard03-b:
    build: 
      context: ./database/mongodb-build
    container_name: shard-03-node-b
    command: mongod --port 27129 --shardsvr --replSet rs-shard-03 --keyFile /data/mongodb-keyfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/persistant/mongodb_cluster_shard03_b_db:/data/db
      - ./database/persistant/mongodb_cluster_shard03_b_config:/data/configdb
    ports:
      - 27129:27129
    restart: always
    networks:
      - gofies
    healthcheck:
        test: ["CMD", "mongosh", "--port", "27129", "--eval", "db.runCommand({ connectionStatus: 1 })"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

networks:
  gofies:
    driver: bridge

volumes:
  mongodb_cluster_router01_db:
  mongodb_cluster_router01_config:
  
  mongodb_cluster_router02_db:
  mongodb_cluster_router02_config:
  
  mongodb_cluster_configsvr01_db:
  mongodb_cluster_configsvr01_config:
  
  mongodb_cluster_configsvr02_db:
  mongodb_cluster_configsvr02_config:
  
  mongodb_cluster_configsvr03_db:
  mongodb_cluster_configsvr03_config:
  
  mongodb_cluster_shard01_a_db:
  mongodb_cluster_shard01_a_config:
  
  mongodb_cluster_shard01_b_db:
  mongodb_cluster_shard01_b_config:
  
  mongodb_cluster_shard02_a_db:
  mongodb_cluster_shard02_a_config:
  
  mongodb_cluster_shard02_b_db:
  mongodb_cluster_shard02_b_config:
  
  mongodb_cluster_shard03_a_db:
  mongodb_cluster_shard03_a_config:
  
  mongodb_cluster_shard03_b_db:
  mongodb_cluster_shard03_b_config: