global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    scheme: https
    static_configs:
      - targets: ['nginx:443']
    metrics_path: '/api/metrics'
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
