# name: CD Pipeline

# on:
#   push:
#     branches:
#       - main # Trigger on pushes to the main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
#           password: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub password

#       - name: Build Docker images
#         run: |
#           docker-compose build

#       - name: Push Docker images
#         run: |
#           docker-compose push

#       - name: Deploy to Server
#         env:
#           HOST: ${{ secrets.DEPLOY_HOST }} # Your server IP or domain
#           USER: ${{ secrets.DEPLOY_USER }} # Your server SSH user
#           SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Your SSH private key
#         run: |
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
#           chmod 600 private_key
#           ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
#             cd /path/to/your/deployment/directory  # Change to your deployment directory
#             docker-compose pull  # Pull the latest images
#             docker-compose up -d  # Restart the containers with the new images
#           EOF
