name: CI Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Grant Docker permissions
        run: |
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Build and start services
        run: |
          make

      - name: Wait for services to be healthy
        run: |
          chmod +x ./health-check.sh
          ./health-check.sh

      - name: Run Frontend Tests
        run: sleep 5

      - name: Run Backend Tests
        run: sleep 5

      - name: Shutdown Docker Compose
        run: docker-compose down

      - name: Upload Test Coverage
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            ./frontend/coverage
            ./backend/coverage