name: CI

on:
  push:
    branches:
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      ai-service:
        image: python:3.9
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v2

      - name: Install AI Service Dependencies
        run: |
          cd ai-service
          pip install -r requirements.txt

      - name: Run AI Tests
        run: |
          cd ai-service
          pytest

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      # Build and start services using Docker Compose
      - name: Build and Run Docker Compose
        run: docker-compose -f docker-compose.yml up --build -d

      # Install dependencies (inside the backend and frontend containers)
      - name: Install Backend Dependencies
        run: docker-compose exec backend npm install

      - name: Install Frontend Dependencies
        run: docker-compose exec frontend npm install

      # Run Tests for both Backend and Frontend
      - name: Run Backend Tests
        run: docker-compose exec backend npm test

      - name: Run Frontend Tests
        run: docker-compose exec frontend npm test

      # Tear down the Docker environment after testing
      - name: Tear Down Docker Compose
        run: docker-compose down
