name: CI Pipeline

on:
  push:
    branches:
      - develop # Trigger the workflow on pushes to the develop branch
  pull_request:
    branches:
      - develop # Trigger on pull requests targeting the develop branch

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   mongo:
    #     image: mongo:latest
    #     ports:
    #       - 27017:27017
    #   postgres:
    #     image: postgres:latest
    #     ports:
    #       - 5432:5432
    #     env:
    #       POSTGRES_DB: your_database${{ secrets.POSTGRES_DB }}
    #       POSTGRES_USER: your_user${{ secrets.DATABASE_USER }}
    #       POSTGRES_PASSWORD: your_password${{ secrets.DATABASE_PASSWORD }}
    #   redis:
    #     image: redis:latest
    #     ports:
    #       - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Run tests
        run: |
          docker-compose up -d
          # Assuming your tests run as a service or command in Docker
          # You may need to adjust the command according to your setup
          docker-compose exec backend npm test

      - name: Tear down
        if: always() # Always run this step, even if the previous steps failed
        run: |
          docker-compose down

      - name: Clean up unused Docker resources
        run: |
          docker system prune -af
