name: CI Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Fix Permissions for Grafana Data (Prevent Exit 1)
        run: |
          sudo chown -R 472:472 ./monitoring/grafana || true
          sudo chmod -R 777 ./monitoring/grafana || true

      - name: Override Docker Compose for CI (Avoid Persistent Volume Issues)
        run: |
          echo "Overriding Docker Compose for CI"
          cat << EOF > docker-compose.override.yml
          version: '3'
          services:
            grafana:
              volumes:
                - /dev/null:/var/lib/grafana
          EOF
          cat docker-compose.override.yml

      - name: Build and start services
        run: |
          make

      - name: Wait for services to be healthy
        run: |
          chmod +x ./health-check.sh
          ./health-check.sh || (docker logs grafana && exit 1)
          docker ps -a


      - name: Run Frontend Tests
        run: |
          echo "Running Frontend Tests..."
          sleep 5

      - name: Run Backend Tests
        run: |
          echo "Running Backend Tests..."
          sleep 5

      - name: Show Logs if Failure Occurs
        if: failure()
        run: |
          docker-compose logs

      - name: Shutdown Docker Compose
        run: docker-compose down

      - name: Upload Test Coverage
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            ./frontend/coverage
            ./backend/coverage