name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2  # Specify the desired version
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Wait for services to be healthy
        run: |
          chmod +x ./health-check.sh
          ./health-check.sh

      - name: Install Frontend Dependencies
        run: |
          docker-compose -f docker-compose.yml exec frontend npm install

      - name: Run Frontend Tests
        run: |
          docker-compose -f docker-compose.yml exec frontend npm test -- --coverage

      - name: Install Backend Dependencies
        run: |
          docker-compose -f docker-compose.yml exec backend npm install

      - name: Run Backend Tests
        run: |
          docker-compose -f docker-compose.yml exec backend npm test -- --coverage

      - name: Shutdown Docker Compose
        run: |
          docker-compose -f docker-compose.yml down

      - name: Upload Test Coverage
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            ./frontend/coverage
            ./backend/coverage
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Node.js for Frontend
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"
  #         cache: "npm"
  #         cache-dependency-path: "./frontend/package-lock.json"

  #     - name: Install and Lint Frontend
  #       working-directory: ./frontend
  #       run: |
  #         npm ci
  #         npm run lint

  #     - name: Set up Node.js for Backend
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "18"
  #         cache: "npm"
  #         cache-dependency-path: "./backend/package-lock.json"

  #     - name: Install and Lint Backend
  #       working-directory: ./backend
  #       run: |
  #         npm ci
  #         npm run lint
